### ISSUE TITLE
runtimeService.startProcessInstanceByMessage(messageName, businessKey, processVariables) start multiple  tasks

### ISSUE THREAD

**Issue by hainanzhong2010** [flowable/flowable-engine#2518] opened 2020-07-23 07:13 UTC
**Describe the bug**
When I try to start a process by message, it creates 2 same tasks

**Expected behavior**
It should be only one user task created

**Code**
runtimeService.startProcessInstanceByMessage(messageName, businessKey, processVariables)，this method was only called once
![image](https://user-images.githubusercontent.com/19727056/88268594-4686ee80-cd05-11ea-96d0-6a6250f24244.png)
![image](https://user-images.githubusercontent.com/19727056/88260676-6e6f5580-ccf7-11ea-886a-bbbe881a6dfb.png)
![image](https://user-images.githubusercontent.com/19727056/88260476-07ea3780-ccf7-11ea-9a7a-a3a19a6311f6.png)

**Additional context**
Flowable 6.4.2 and 6.5.0

**Comment by tijsrademakers** [comment] 2020-08-09 10:06
Hi,

Please provide a unit test showing the issue. We can't reproduce this issue, so closing it for now. Please reopen with more details and a unit test when applicable.

Best regards

**Closed by tijsrademakers** 2020-08-09 10:06 UTC
