### ISSUE TITLE
flowable-idm in version 6 add group functionality doesn't work

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#168] opened 2017-01-20 21:01 UTC
flowable-idm in version 6 add group functionality doesn't work

**Comment by tijsrademakers** [comment] 2017-01-20 21:05
Did you check the current master version? I'm able to create groups.

**Comment by mgrouch** [comment] 2017-01-20 21:07
Great. I saw it in RC1

**Comment by tijsrademakers** [comment] 2017-01-23 10:14
Closing it, can you please reopen when the issue is still there on the master version?

**Closed by tijsrademakers** 2017-01-23 10:14 UTC
