### ISSUE TITLE
Drools  If the DRL file is automatically deployed, click the deploy button.

### ISSUE THREAD

**Issue by huojg** [flowable/flowable-engine#858] opened 2018-03-05 10:39 UTC
If the DRL file is automatically deployed, click the deploy button.

**Comment by tijsrademakers** [comment] 2018-05-13 09:13
Closing the issue, because the issue is not described in a way we can do something with it. Please reopen with a clear description of the issue when it’s still relevant.

**Closed by tijsrademakers** 2018-05-13 09:13 UTC
