### ISSUE TITLE
Flowable Admin - Process Engine - Migrate process instance - Only 10 versions avaliable

### ISSUE THREAD

**Issue by tiarossi** [flowable/flowable-engine#1770] opened 2019-05-27 18:05 UTC
At Migrate Process Instance dialog Floable Admin displays only the first ten process definitions of an app.

![image](https://user-images.githubusercontent.com/477378/58434062-4010ce80-8090-11e9-80ba-1e87cba5c7b4.png)

**Comment by tijsrademakers** [comment] 2019-08-13 07:14
Thanks for reporting, the issue is fixed now on master

**Closed by tijsrademakers** 2019-08-13 07:14 UTC

**Comment by mailforalvin** [comment] 2020-03-03 05:53
I am facing the same issue. Only 10 process definitions are listed. Could you please help resolve this?
