### ISSUE TITLE
Query process handles reporting null pointer

### ISSUE THREAD

**Issue by cdk3344520** [flowable/flowable-engine#3551] opened 2022-12-15 01:46 UTC
**Describe the bug**
After the process instance with countersignature is deleted, a null pointer exception occurs when querying process variables

**Comment by Abhijeetmishr** [comment] 2023-01-07 12:18
Hey @cdk3344520 can I pick up this issue.

**Comment by filiphr** [comment] 2023-01-09 07:02
@cdk3344520 can you please provide a bit more details about this issue. An example of how to get the null pointer exception would be good.

@Abhijeetmishr do you know how to reproduce this?

**Comment by Abhijeetmishr** [comment] 2023-01-09 15:58
@filiphr would be great if you guide, I will invesgtigate further and will do some poc also.

**Comment by filiphr** [comment] 2023-01-09 16:01
@Abhijeetmishr I cannot guide you for this one, because I myself do not know what the problem is. I'll leave it up to @cdk3344520 to provide an example. If they do not, then we will go ahead and close this issue

**Comment by PinoEire** [comment] 2023-05-03 07:44
Hi there. I’m looking at Flowable reliability and support to evaluate its implementation in a critical system.

I’m worried about finding bugs like this one that have no answers and is still open after a long time. Is there a rationale behind this?

**Comment by filiphr** [comment] 2023-05-03 07:56
Closing this issue since it was never explained how we need to reproduce this problem. @PinoEire I don't understand what you mean with your question. As you can see for this issue we asked for feedback that we never got back.

**Closed by filiphr** 2023-05-03 07:56 UTC
