### ISSUE TITLE
In flowable-task on process diagram add ability to restart workflow from selected step

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#190] opened 2017-01-31 05:32 UTC
In flowable-task on process diagram add ability to restart workflow from selected step

**Comment by paulhh** [comment] 2017-01-31 09:17
Closing as not a bug and no discussion on the forums for the feature (see https://github.com/flowable/flowable-engine/wiki).

**Closed by paulhh** 2017-01-31 09:17 UTC
