### ISSUE TITLE
Upgrade Fails entitylink schema from 6.1.2.0 to 6.6.0.0 on Oracle

### ISSUE THREAD

**Issue by buksvdl** [flowable/flowable-engine#2814] opened 2021-02-16 07:42 UTC
```
21-02-16 Tue 09:35:45.542 INFO  1 --- [    main] EntityLinkDbSchemaManager                : upgrading flowable entitylink schema from 6.1.2.0 to 6.6.0.0
21-02-16 Tue 09:35:45.543 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6120 -> 6200. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.545 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6200 -> 6210. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.547 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6210 -> 6300. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.548 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6300 -> 6301. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.550 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6301 -> 6310. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.551 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6310 -> 6320. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.553 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6320 -> 6400. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.554 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6400 -> 6410. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.556 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6410 -> 6411. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.556 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.oracle.upgradestep.6410.to.6411.entitylink.sql
21-02-16 Tue 09:35:45.610 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6411 -> 6412. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.612 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6411.to.6412.entitylink.sql
21-02-16 Tue 09:35:45.613 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6412 -> 6413. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.614 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6412.to.6413.entitylink.sql
21-02-16 Tue 09:35:45.615 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6413 -> 6500. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.617 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6413.to.6500.entitylink.sql
21-02-16 Tue 09:35:45.622 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6500 -> 6501. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.623 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6500.to.6501.entitylink.sql
21-02-16 Tue 09:35:45.625 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6501 -> 6502. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.626 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6501.to.6502.entitylink.sql
21-02-16 Tue 09:35:45.628 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6502 -> 6503. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.629 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6502.to.6503.entitylink.sql
21-02-16 Tue 09:35:45.630 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6503 -> 6504. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.632 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6503.to.6504.entitylink.sql
21-02-16 Tue 09:35:45.633 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6504 -> 6505. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.634 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6504.to.6505.entitylink.sql
21-02-16 Tue 09:35:45.635 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6505 -> 6506. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.637 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6505.to.6506.entitylink.sql
21-02-16 Tue 09:35:45.638 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6506 -> 6510. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.640 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.all.upgradestep.6506.to.6510.entitylink.sql
21-02-16 Tue 09:35:45.641 INFO  1 --- [    main] EntityLinkDbSchemaManager                : Upgrade needed: 6510 -> 6511. Looking for schema update resource for component 'entitylink'
21-02-16 Tue 09:35:45.641 INFO  1 --- [    main] EntityLinkDbSchemaManager                : performing upgrade on entitylink with resource org/flowable/entitylink/service/db/upgrade/flowable.oracle.upgradestep.6510.to.6511.entitylink.sql
21-02-16 Tue 09:35:45.659 ERROR 1 --- [    main] EntityLinkDbSchemaManager                : problem during schema upgrade, statement alter table ACT_RU_ENTITYLINK add ROOT_SCOPE_ID_ NVARCHAR2(255)
java.sql.SQLException: ORA-01430: column being added already exists in table
```

One of the upgrades must've created the col already since it fails even when i delete the col prior to startup.

**Comment by buksvdl** [comment] 2021-02-16 07:47
`update ACT_GE_PROPERTY set VALUE_ = '6.4.1.1' where NAME_ = 'entitylink.schema.version';`

Issue is that there is no INSERT anywhere in scope

**Comment by tijsrademakers** [comment] 2021-02-16 07:59
Hi,

The problem with the ROOT_SCOPE_ID_ already existing is strange, because there's no other upgrade script that adds it. Is the ACT_RU_ENTITYLINK table existing in your database? Does it already have the ROOT_SCOPE_ID_ column? You are correct that the upgrade script is not correctly inserting the entitylink.schema.version property, we will look into that.

Best regards

**Comment by tijsrademakers** [comment] 2021-02-17 14:18
After checking this, when upgrading Flowable from an old version to 6.6.0.0 the entity link create sql script will be executed and that has all the table and entitylink.schema.version property logic. How are you doing the upgrade? Because we can't reproduce this issue. Therefore closing the issue here for now.

**Closed by tijsrademakers** 2021-02-17 14:18 UTC
