### ISSUE TITLE
Exception raised when attaching a file

### ISSUE THREAD

**Issue by reece** [flowable/flowable-engine#2929] opened 2021-05-17 00:07 UTC
**Describe the bug**
When trying to attach a file to a task, I get a java exception

**Expected behavior**
File attachment

**Reproduction**
Following https://blog.flowable.org/2020/10/07/flowable-6-instant-gratification/

$ docker run -p8080:8080 flowable/flowable-ui   # image id 5eb35bf8d8dc

Then at http://localhost:8080/flowable-ui/:
* login as admin/test
* click Task App
* click Create Task
* Name="My First Task"
* Click Create
* Click Add a document and share the knowledge
* Click Select a file
* Select a file 

This exception is then raised:

```
2021-05-17 00:04:48.977 ERROR 1 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/flowable-ui] threw exception [Request processing failed; nested exception is org.flowable.content.api.ContentStorageException: Could not write content to /data/task-content/5ca71419-b6a3-11eb-8ec7-0242ac110002/7ee47d6d-b6a3-11eb-8ec7-0242ac110002] with root cause

java.io.FileNotFoundException: data/task-content/5ca71419-b6a3-11eb-8ec7-0242ac110002/7ee47d6d-b6a3-11eb-8ec7-0242ac110002 (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method) ~[na:na]
	at java.base/java.io.FileOutputStream.open(Unknown Source) ~[na:na]
	at java.base/java.io.FileOutputStream.<init>(Unknown Source) ~[na:na]
	at org.flowable.content.engine.impl.fs.SimpleFileSystemContentStorage.createContentObject(SimpleFileSystemContentStorage.java:106) ~[flowable-content-engine-6.6.0.jar:6.6.0]
        ⋮
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

I've tried several file sizes and types

**Comment by 4gsim** [comment] 2021-05-19 13:29
The problem is that the application is run with flowable user in the container, but that user cannot create the data content folder.

**Comment by yvoswillens** [comment] 2021-05-19 14:25
Hi,

@4gsim is right. A folder with the required permissions is missing. I will add this to the next image version.
In the meantime you can mount a volume and set this content location when starting the container for example like this;

```
mkdir /tmp/flowable_data

docker run -p8080:8080 \
 -v /tmp/flowable_data:/flowable_data \
 flowable/flowable-ui --flowable.content.storage.root-folder=/flowable_data
```

**Comment by yvoswillens** [comment] 2021-05-19 15:04
This is fixed now on master and will be published as part of the next release.

**Closed by yvoswillens** 2021-05-19 15:04 UTC

**Comment by reece** [comment] 2021-05-20 00:14
The workaround in https://github.com/flowable/flowable-engine/issues/2929#issuecomment-844156721 didn't work for me. I'll try again when the new docker image is out.

**Comment by yvoswillens** [comment] 2021-05-20 05:44
I just verified the proposed workaround and it should work.
If you want you can start a topic in the Flowable forum and investigate why it does not work for you.
