### ISSUE TITLE
Docker: Unable to customise port number

### ISSUE THREAD

**Issue by srinathganesh** [flowable/flowable-engine#1719] opened 2019-04-27 10:34 UTC
Say port 8080 is not available and we would like change it, since we are deploying it via docker we could do this

```
services:
  flowable:
    image: flowable/all-in-one
    ports:
      - 1111:8080
```

But when I visit the url
`http://localhost:1111/flowable-modeler/`

it redirects me to the url
`http://localhost:8080/flowable-idm/#/login?redirectOnAuthSuccess=true&redirectUrl=http://localhost:1111/flowable-modeler/`

looks like its been hard-coded to 8080

**Comment by akaitoua** [comment] 2019-04-30 05:29
You should set the environment variables to check it out in here for an example: https://hub.docker.com/r/flowable/flowable-modeler/

Required environment properties;
FLOWABLE_COMMON_APP_IDM-URL: full url of the IDM app; used for server to server communication
FLOWABLE_COMMON_APP_IDM-ADMIN_USER: IDM admin user (when running with default configuration: admin)
FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD: IDM admin password (when running with default configuration: test)

Optional environment properties;
SERVER_PORT: the Tomcat server port (default 8888)
FLOWABLE_COMMON_APP_IDM-REDIRECT-URL: full url of the IDM app; used for client browser redirection (f.e. http://localhost:8080/flowable-idm)
FLOWABLE_MODELER_APP_DEPLOYMENT-API-URL: full url of Flowable Process Engine API (f.e. http://flowable-task-app:9999/flowable-task/app-api)
SPRING_DATASOURCE_DRIVER-CLASS-NAME: f.e. org.postgresql.Driver
SPRING_DATASOURCE_URL: f.e. jdbc:postgresql://:5432/flowable
SPRING_DATASOURCE_USERNAME: f.e. flowable
SPRING_DATASOURCE_PASSWORD: f.e. flowable

**Comment by dbmalkovsky** [comment] 2019-05-10 18:11
Closing as the follow up comment and link provides the necessary information.

**Closed by dbmalkovsky** 2019-05-10 18:11 UTC

**Comment by srinathganesh** [comment] 2019-10-15 11:17
this is my docker compose, I am still facing this problem. any idea what am i missing? 
`
version: '3'

services:
  flowable:
    image: flowable/all-in-one
    environment:
      - FLOWABLE_COMMON_APP_IDM-URL=http://flowable:8080/flowable-idm
      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://a.b.com:4000/flowable-idm
      - FLOWABLE_COMMON_APP_IDM-ADMIN_USER=admin
      - FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD=test
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://a_postgres:5432/flowable
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
    extra_hosts:
      - "a.b.com:192.168.1.5"

  flowable_nginx:
    build: ./nginx
    depends_on:
      - flowable
    ports:
      - ${FLOWABLE_PORT}:80
    command: nginx -g 'daemon off;'
`

**Comment by techorix** [comment] 2020-02-06 10:21
I can confirm that running 
docker run -e FLOWABLE_COMMON_APP_IDM-URL=http://localhost:9090/flowable-idm -e FLOWABLE_COMMON_APP_IDM-ADMIN_USER=admin -e FLOWABLE_COMMON_APP_IDM-ADMIN_PASSWORD=test -e FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://localhost:9090/flowable-idm -p9090:8080 flowable/all-in-one

Will in fact forward you to the flowable-modeler if you enter http://localhost:9090/flowable-modeler

But the login will *fail* because the port is also used within the docker container now. Setting SERVER_PORT has no effect, by the way and the example on docker-hub you mentioned does not work as it uses -p8888:8888 instead of -p8080:8080. 

Here is the exception:
2020-02-06 10:18:50.833  INFO 1 --- [nio-8080-exec-7] o.s.w.s.DispatcherServlet                : Initializing Servlet 'dispatcherServlet'
2020-02-06 10:18:50.840  INFO 1 --- [nio-8080-exec-7] o.s.w.s.DispatcherServlet                : Completed initialization in 7 ms
2020-02-06 10:18:54.564  WARN 1 --- [nio-8080-exec-6] o.f.u.c.s.i.RemoteIdmServiceImpl         : Exception while getting token

org.apache.http.conn.HttpHostConnectException: Connect to localhost:9090 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.11.jar:4.5.11]
        at org.flowable.ui.common.service.idm.RemoteIdmServiceImpl.callRemoteIdmService(RemoteIdmServiceImpl.java:152) [flowable-ui-common-6.5.0.jar:6.5.0]
        at org.flowable.ui.common.service.idm.RemoteIdmServiceImpl.getToken(RemoteIdmServiceImpl.java:77) [flowable-ui-common-6.5.0.jar:6.5.0]
        at org.flowable.ui.common.filter.FlowableCookieFilter$1.load(FlowableCookieFilter.java:103) [flowable-ui-common-6.5.0.jar:6.5.0]
        at org.flowable.ui.common.filter.FlowableCookieFilter$1.load(FlowableCookieFilter.java:99) [flowable-ui-common-6.5.0.jar:6.5.0]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) [guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) [guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) [guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) [guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951) [guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974) [guava-28.2-jre.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958) [guava-28.2-jre.jar:?]
        at org.flowable.ui.common.filter.FlowableCookieFilter.getValidToken(FlowableCookieFilter.java:185) [flowable-ui-common-6.5.0.jar:6.5.0]
        at org.flowable.ui.common.filter.FlowableCookieFilter.doFilterInternal(FlowableCookieFilter.java:144) [flowable-ui-common-6.5.0.jar:6.5.0]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.14]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.14]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.14]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121) [spring-boot-2.2.2.RELEASE.jar:2.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.14]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108) [spring-boot-actuator-2.2.2.RELEASE.jar:2.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.14]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.2.RELEASE.jar:5.2.2.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.14]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.14]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.14]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.14]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.14]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.14]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668) [catalina.jar:9.0.14]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.14]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.14]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.14]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.14]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) [tomcat-coyote.jar:9.0.14]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417) [tomcat-coyote.jar:9.0.14]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.14]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.14]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
        at java.net.Socket.connect(Unknown Source) ~[?:?]
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.11.jar:4.5.11]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.11.jar:4.5.11]
        ... 81 more

**Comment by yvoswillens** [comment] 2020-02-06 10:50
Hi.

What do you mean with;
> All off the stuff on the flowable-modeler dockerhub page doesn't work out of the box, though (anymore).

This issue was about the ```all-in-one``` image. This runs the Flowable UI apps on a Tomcat servlet container. This means some of the Spring Boot (standalone) application properties do not apply. Like ```SERVER_PORT```.
