### ISSUE TITLE
JSon expression language is not evaluated when using flowable-spring-boot-starter and flowable-http 

### ISSUE THREAD

**Issue by j-jeurissen** [flowable/flowable-engine#2112] opened 2020-01-08 10:02 UTC
**Describe the bug**
When we use JSON expression language, with the flowable embedded engine, the used JSon EL is not evaluated correctly. 

**Expected behavior**
When I import the exact same BPMN flow xml in the all-in-one docker image, it works as expected.

**Code**
I've created a demo project to illustrate the issue:
https://github.com/EnlightenedSoftware/flowable-orchestrator-demo

**Additional context**
We are using the maven flowable-spring-boot-starter, flowable-http dependencies(version 6.4.2) and the h2 database.

**Comment by tijsrademakers** [comment] 2020-01-18 21:24
Hi,

The problem is that the JUEL expression language has issues with method overloading and that's why the wrong method is selected. We will look for ways to support getting the first element of an JSON array in an expression, but closing this issue for now.

**Closed by tijsrademakers** 2020-01-18 21:24 UTC
