### ISSUE TITLE
HistoricProcessInstanceQuery also query task variable

### ISSUE THREAD

**Issue by ningpp** [flowable/flowable-engine#3121] opened 2021-11-25 01:49 UTC
**Describe the bug**
when use HistoricProcessInstanceQuery with variable value,
it also query query task variable with the same name

**Expected behavior**
HistoricProcessInstanceQuery only query process variable

**Code**
```
HistoricProcessInstanceQuery query = historyService
          .createHistoricProcessInstanceQuery()
          .processInstanceId("abc")
.includeProcessVariables();
query.variableValueEquals("process_variable", "process_variable_value");
query.count();
```
this query produce a sql  : 
```
select
    count(distinct RES.ID_)
from
    ACT_HI_PROCINST RES
    left outer join ACT_RE_PROCDEF DEF on RES.PROC_DEF_ID_ = DEF.ID_
    inner join ACT_HI_VARINST A0 on RES.PROC_INST_ID_ = A0.PROC_INST_ID_
WHERE
    RES.PROC_INST_ID_ = ?
    and A0.NAME_ = ?
    and A0.VAR_TYPE_ = ?
    and (A0.TEXT_ = ?)
```

the right sql should be 

```
select
    count(distinct RES.ID_)
from
    ACT_HI_PROCINST RES
    left outer join ACT_RE_PROCDEF DEF on RES.PROC_DEF_ID_ = DEF.ID_
    inner join ACT_HI_VARINST A0 on RES.PROC_INST_ID_ = A0.PROC_INST_ID_
WHERE
    RES.PROC_INST_ID_ = ?
    and A0.NAME_ = ?
    and A0.VAR_TYPE_ = ?
    and (A0.TEXT_ = ?)
    and A0.TASK_ID_ IS NULL
```

**Additional context**
flowable:  6.6.0 ,  6.7.0   
database: mysql

**Comment by ningpp** [comment] 2021-11-26 03:26
hello, i need your help

**Comment by tijsrademakers** [comment] 2021-11-26 16:40
Hi @ningpp , we think your analysis is correct, thanks for creating the issue. We will look into it.

**Comment by ningpp** [comment] 2021-12-16 13:19
hello,  any progress?

**Comment by tijsrademakers** [comment] 2021-12-16 13:20
Hi @ningpp, not yet, but it's on our list to get resolved

**Comment by ningpp** [comment] 2021-12-16 13:22
thank you

**Comment by tijsrademakers** [comment] 2021-12-23 08:58
Hi @ningpp , the issue is fixed now. Thanks for reporting

**Closed by tijsrademakers** 2021-12-23 08:58 UTC
