### ISSUE TITLE
Case Model errors when validating

### ISSUE THREAD

**Issue by railrhoad** [flowable/flowable-engine#1555] opened 2019-01-25 20:57 UTC
Grabbed the 6.4.1 wars ,deployed them to Tomcat, and used the default H2 connection.  From the modeler I started a new Case Model and just attempted to validate the new model and get this consistently...

2019-01-25 15:52:51.061 ERROR 6688 --- [io-8080-exec-10] o.f.e.l.j.c.BpmnJsonConverter            : Error converting CasePlanModel
java.lang.NullPointerException: null
        at org.flowable.editor.language.json.converter.BpmnJsonConverter.processJsonElements(BpmnJsonConverter.java:730) [flowable-json-converter-6.4.1.jar:6.4.1]
        at org.flowable.editor.language.json.converter.BpmnJsonConverter.convertToBpmnModel(BpmnJsonConverter.java:631) [flowable-json-converter-6.4.1.jar:6.4.1]
        at org.flowable.editor.language.json.converter.BpmnJsonConverter.convertToBpmnModel(BpmnJsonConverter.java:459) [flowable-json-converter-6.4.1.jar:6.4.1]
        at org.flowable.ui.modeler.rest.app.ModelValidationRestResource.validate(ModelValidationRestResource.java:41) [flowable-ui-modeler-rest-6.4.1.jar:6.4.1]

**Comment by tijsrademakers** [comment] 2019-01-26 13:56
Duplicate of #1414

**Closed by tijsrademakers** 2019-01-26 13:56 UTC

**Comment by railrhoad** [comment] 2019-01-28 13:20
We were also running into this.  Is there a previous version we could rollback to to test out the CMMN workflows?  I know this issue is also in 6.3.1.

**Comment by tijsrademakers** [comment] 2019-01-28 14:04
Validation of CMMN case models is not yet supported

**Comment by ZideneAjlani** [comment] 2020-05-13 15:01
I am integrating Flowable CMMN for one of my solutions, I have the same problem of model validation.
Have you any idea when the CMMN validation will be integrated and for which release ?

Thank you in advance.
