### ISSUE TITLE
Whether to support rollback

### ISSUE THREAD

**Issue by idawnorg** [flowable/flowable-engine#203] opened 2017-02-06 10:29 UTC
Whether to support rollback？What is Related API ?

**Comment by tijsrademakers** [comment] 2017-02-06 12:42
Ehm, can you please elaborate a bit more?

**Comment by idawnorg** [comment] 2017-02-07 00:51
Scrolls the current task to the executed task node

**Comment by tijsrademakers** [comment] 2017-02-07 08:24
Really no idea what the issue is. Closing the issue for now. Please reopen with detailed information about the issue when applicable.

**Closed by tijsrademakers** 2017-02-07 08:24 UTC

**Comment by idawnorg** [comment] 2017-02-09 07:59
thanks
