### ISSUE TITLE
Add 'validate' button in process workflow editor flowable-modeler

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#166] opened 2017-01-20 20:58 UTC
Add 'validate' button in process workflow editor flowable-modeler
to allow to see workflow design errors.

**Comment by paulhh** [comment] 2017-01-31 09:21
Closing as not a bug and no discussion on the forums for the feature (see https://github.com/flowable/flowable-engine/wiki).

**Closed by paulhh** 2017-01-31 09:21 UTC
