### ISSUE TITLE
Error trying to deploy flowable chart using HELM 3

### ISSUE THREAD

**Issue by gmalanga** [flowable/flowable-engine#2175] opened 2020-02-17 17:30 UTC
I am trying to deploy flowable using helm chart 

`helm install flowable/flowable 
         --name-template flowable 
         -f dpa-flowable/values-flowable.yaml 
         -n dpa-flowable`

and I am getting the following error:

`Error: file '/Users/gmalanga/Library/Caches/helm/repository/flowable-6.5.0.tgz' does not appear to be a gzipped archive; got 'application/octet-stream'`

The same command was working in December 2019, and I did not change any configuration to the YAML file supplied in the command.
I am using helm v. 3.1.0 and flowable v. 6.5.0.

Thanks for your help.

**Comment by tstephen** [comment] 2020-02-17 22:43
@yvoswillens set up the Helm repo at `https://flowable.org/helm/` but that was pre 6.5.0 release. I assume that is the repo you have @gmalanga?

Since then the .org site has migrated to [https://flowable.com/open-source/](https://flowable.com/open-source/) and [https://flowable.com/helm/](https://flowable.com/helm/) gives a `404` and [https://flowable.com/open-source/helm/](https://flowable.com/open-source/helm/) a `403`.

Whilst someone from flowable will need to tell us the new repo location, you can build and host the chart on your own repo, which simply requires a web server that is accessible from your helm control machine. Assuming F_HOME is the dir where you have checked out the flowable source:

```
$ cd $F_HOME/k8s
$ helm package flowable/
Successfully packaged chart and saved it to: /path/to/f_home/k8s/flowable-0.1.0.tgz
$ cd flowable/
$ helm repo index .
```
This will produce a `.tgz` file in the `k8s` dir and an `index.yaml` in `flowable` that you can host somewhere.

**Comment by yvoswillens** [comment] 2020-02-18 08:27
Hi,

The repo should still be accessible. Please verify if the steps below are still working correctly.

```
helm repo remove flowable
```
```
helm repo add flowable https://flowable.org/helm/
```
```
helm search -l flowable/flowable
```

Let me know if this is not the case; then I'll have to investigate it further.

**Comment by gmalanga** [comment] 2020-02-18 09:46
@yvoswillens Here is the output from the steps you told me:

`helm search repo flowable/flowable
NAME             	CHART VERSION	APP VERSION	DESCRIPTION 
flowable/flowable	6.5.0        	6.5.0      	A Flowable Helm chart for Kubernetes`

@tstephen @yvoswillens Not sure if this is an issue of finding the repo, I presume this is something related to the ContentType of the .gtz file; I found a similar issue here https://github.com/helm/helm/issues/2916.

The last comment is from 6 days ago and it says:

> The gzip is a legit one, but when helm check the content type got application/octet-stream and not x-gzip.
> I think the problem is in this check in the file `chart/loader/archive.go`:
> 
> `if contentType := http.DetectContentType(buffer); contentType != "application/x-gzip" `
>
> That should accept octect/stream too

**Comment by tstephen** [comment] 2020-02-18 09:46
Ah ok, you're right the `flowable.org` repo is still there, I was doing a test via browser. Thanks @yvoswillens

**Comment by yvoswillens** [comment] 2020-02-18 09:59
@gmalanga is the issue resolved?

**Comment by gmalanga** [comment] 2020-02-18 10:02
@yvoswillens Nope, same message error. 

Could it be due to the way you have packaged the helm chart?

**Comment by yvoswillens** [comment] 2020-02-18 10:07
The Helm chart is a Helm 2 chart. Not a Helm 3 chart. This could be causing the issue.

**Comment by tstephen** [comment] 2020-02-18 10:11
The `flowable-6.5.0.tgz` I just pulled from the repo is just yaml (try runing through cat).

**Comment by yvoswillens** [comment] 2020-02-18 10:17
After cleaning the local cache and fetching the chart with

```
helm inspect flowable/flowable --debug
```

the Chart archive (.helm/cache/archive/flowable-6.5.0.tgz) looks fine.

Can you verify this?

**Comment by gmalanga** [comment] 2020-02-18 10:28
After removing the repo and importing it again, I am getting the same issue:

`helm inspect chart flowable/flowable --debug
Error: file '/Users/gmalanga/Library/Caches/helm/repository/flowable-6.5.0.tgz' does not appear to be a gzipped archive; got 'application/octet-stream'
helm.go:75: [debug] file '/Users/gmalanga/Library/Caches/helm/repository/flowable-6.5.0.tgz' does not appear to be a gzipped archive; got 'application/octet-stream'`

**Comment by yvoswillens** [comment] 2020-02-18 10:31
Did you see my response regarding Helm 2 / 3? Helm 3 is not completely backwards compatible with version 2.

**Comment by gmalanga** [comment] 2020-02-18 10:36
@yvoswillens Yes, I saw your comment. Does it mean that you are not going to support Helm 3?

This is weird because the previous Flowable release was working correctly with Helm 3.

**Comment by yvoswillens** [comment] 2020-02-18 10:41
We will definitely look at Helm 3 support for the next release. But when releasing 6.5.0 Helm 3 was just released and we made the decision not to support it 'officially'.
If there is an obvious cause that is causing this gzip issue then I will try and fix it. But with Helm 2 I cannot reproduce it.

**Comment by yvoswillens** [comment] 2020-02-18 11:04
I verified the downloaded file.
```
wget http://flowable.org/helm/flowable-6.5.0.tgz
```
```
file flowable-6.5.0.tgz
flowable-6.5.0.tgz: gzip compressed data, extra field, has comment, original size modulo 2^32 164864
```

I'm closing the issue for now because everything seems in order when using Helm 2. 
If Helm 3 is causing this issue please install using the Chart repo files;

https://github.com/flowable/flowable-engine/tree/master/k8s/flowable

We aim to provide Helm 3 support when release the next chart version.

Feel free to reopen this issue if something else is causing this issue.

**Comment by tstephen** [comment] 2020-02-18 12:35
@yvoswillens I'm aware of some differences between Helm 2 & 3 (for example: no more Tiller - yay!) but I've not come across any differences in the actual charts.Apparently there are differences in the packaging of charts but I've been happily packaging the existing 6.5.0 code using helm 3 and deploying it (using helm 3) for a while.

**Comment by yvoswillens** [comment] 2020-02-18 12:37
Yes .. sure .. I'm not saying that it shouldn't work; just that I haven't tested it / used it myself.
Are you experiencing the same issue? (when using the Helm tools)

**Comment by tstephen** [comment] 2020-02-18 12:41
Yes, I see the same:
```
$ helm install --name-template flowable650  -f cfg/flowable-values.yaml flowable/flowable
Error: file '/home/tstephen/.cache/helm/repository/flowable-6.5.0.tgz' does not appear to be a gzipped archive; got 'application/octet-stream'
```

(Also I was editing my last post when you replied - what do you think about the helm3 folder idea?)

**Comment by yvoswillens** [comment] 2020-02-18 12:42
But also with Helm 3; not 2?

**Comment by tstephen** [comment] 2020-02-18 12:43
Yes, with Helm 3

**Comment by yvoswillens** [comment] 2020-02-18 13:20
Something related to fetching the chart with Helm 3 is causing this. 
I will investigate the web server part of this further (but the first glance did not reveal any obvious issues).

In the meantime deploying with Helm 3 can be done this way (download and install seperately)

```
wget http://flowable.org/helm/flowable-6.5.0.tgz
```
```
helm install flowable flowable-6.5.0.tgz
```

**Comment by tstephen** [comment] 2020-02-18 14:34
I did the following on top of flowable-0.1.0 that I built and deployed with helm 3 and it was successful:

```
wget http://flowable.org/helm/flowable-6.5.0.tgz
helm upgrade flowable flowable-6.5.0.tgz
$ helm upgrade flowable flowable-6.5.0.tgz 
Release "flowable" has been upgraded. Happy Helming!
NAME: flowable
LAST DEPLOYED: Tue Feb 18 14:31:02 2020
NAMESPACE: default
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
...
```
On killing the pod a new one is created with the latest revision and starts up fine.

**Comment by yvoswillens** [comment] 2020-03-27 14:51
The current published Flowable Helm chart was packaged using Helm 2.
Installing it from the repo using Helm 2 works. Installing from the repo using Helm 3 can cause issues. Installing the downloaded (or build) chart file works (with both Helm 2 and 3).
We've done some tests with building and publishing using Helm 3. This seems to solve the issues.
For the next release we will use Helm 3 when building and publishing the chart.

**Closed by yvoswillens** 2020-03-27 14:51 UTC
