### ISSUE TITLE
Create common CSS for all flowable web apps for easy styling

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#164] opened 2017-01-20 20:52 UTC
Flowable 6 UI consists of 5 separate web applications each with its own CSS.
Why don't they have common CSS? It seems the is no style re-use and it makes difficult to integrate with other websites requiring consistent look and feel.

It would be nice if that common CSS override would be in some well documented location on classpath so to change look and feel a developer would just include additional CSS into well known location on a classpath.

Thanks

**Comment by paulhh** [comment] 2017-01-31 09:21
Closing as not a bug and no discussion on the forums for the feature (see https://github.com/flowable/flowable-engine/wiki).

**Closed by paulhh** 2017-01-31 09:21 UTC
