### ISSUE TITLE
Test failed due to wrong assumption/usage of standard library API.

### ISSUE THREAD

**Issue by contextshuffling** [flowable/flowable-engine#2203] opened 2020-03-03 23:14 UTC
**Describe the bug**
`org.flowable.cmmn.test.el.VariableFunctionDelegatesTest#testVariableEquals` failed with the following stacktraces:
```
org.flowable.common.engine.impl.javax.el.ELException: Parameters for function 'variables:equals' do not match
        at org.flowable.common.engine.impl.de.odysseus.el.tree.Tree.bind(Tree.java:132)
        at org.flowable.common.engine.impl.de.odysseus.el.TreeValueExpression.<init>(TreeValueExpression.java:73)
        at org.flowable.common.engine.impl.de.odysseus.el.ExpressionFactoryImpl.createValueExpression(ExpressionFactoryImpl.java:444)
        at org.flowable.common.engine.impl.de.odysseus.el.ExpressionFactoryImpl.createValueExpression(ExpressionFactoryImpl.java:77)
        at org.flowable.common.engine.impl.el.DefaultExpressionManager.createExpression(DefaultExpressionManager.java:88)
        at org.flowable.cmmn.engine.impl.agenda.operation.EvaluateCriteriaOperation.evaluateSentryIfPart(EvaluateCriteriaOperation.java:359)
        at org.flowable.cmmn.engine.impl.agenda.operation.EvaluateCriteriaOperation.evaluateCriteria(EvaluateCriteriaOperation.java:257)
        at org.flowable.cmmn.engine.impl.agenda.operation.EvaluateCriteriaOperation.evaluateEntryCriteria(EvaluateCriteriaOperation.java:222)
        at org.flowable.cmmn.engine.impl.agenda.operation.EvaluateCriteriaOperation.evaluatePlanItemsCriteria(EvaluateCriteriaOperation.java:135)
        at org.flowable.cmmn.engine.impl.agenda.operation.EvaluateCriteriaOperation.run(EvaluateCriteriaOperation.java:92)
        at org.flowable.cmmn.engine.impl.interceptor.CmmnCommandInvoker.executeOperations(CmmnCommandInvoker.java:64)
        at org.flowable.cmmn.engine.impl.interceptor.CmmnCommandInvoker.execute(CmmnCommandInvoker.java:50)
        at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
        at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:72)
        at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
        at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
        at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
        at org.flowable.cmmn.engine.impl.runtime.CmmnRuntimeServiceImpl.startCaseInstance(CmmnRuntimeServiceImpl.java:93)
        at org.flowable.cmmn.engine.impl.runtime.CaseInstanceBuilderImpl.start(CaseInstanceBuilderImpl.java:174)
        at org.flowable.cmmn.test.el.VariableFunctionDelegatesTest.testVariableEquals(VariableFunctionDelegatesTest.java:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Expected behavior**
Tests should always passes, if no code changes are made.

**Analysis**
So I start to check when this erroneous method is reflected and I found `java.lang.Class.getMethods` is invoked here:
https://github.com/flowable/flowable-engine/blob/9b647e3c9a10ee28d8f290f6ea651aa478346860/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/function/AbstractFlowableShortHandExpressionFunction.java#L101

I also checked the log for where the method `equals` came from and then I found the following:
https://github.com/flowable/flowable-engine/blob/758388c98b2cbb22afb3d2ff3de3c27aaf55d7b3/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/function/VariableEqualsExpressionFunction.java#L32

So in this test, it is actually looking for `VariableEqualsExpressionFunction#equals` but the function above actually gives back `public boolean java.lang.Object.equals(java.lang.Object)`.

In the comment, it is also noted here:
 https://github.com/flowable/flowable-engine/blob/9b647e3c9a10ee28d8f290f6ea651aa478346860/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/el/function/AbstractFlowableShortHandExpressionFunction.java#L96

However, the test implemented `equals` which has the same name (different signature) with `Object`. 

So from my perspective, the methods that really should be used here is `java.Class.getDeclaredMethods` as the document indicates: "*Returns an array containing Method objects reflecting all the declared methods of the class or interface represented by this Class object, including public, protected, default (package) access, and private methods,* **but excluding inherited methods**"

**Comment by tijsrademakers** [comment] 2020-03-04 07:45
@contextshuffling thanks for raising the issue. Does this test fail for you always? Do you use a specific JDK when testing this? I can't reproduce the issue yet.

**Comment by tijsrademakers** [comment] 2020-03-19 15:23
The PR was merged, so should be ok now.

**Closed by tijsrademakers** 2020-03-19 15:23 UTC
