### ISSUE TITLE
ProcessDefinitionQuery.latestVersion() is useless to .active()

### ISSUE THREAD

**Issue by sscfaith** [flowable/flowable-engine#2751] opened 2020-12-22 03:53 UTC
**Describe the bug**
There are two versions of my deployment process and v2 is suspended. if I use
```java
 ProcessDefinitionQuery processDefinitionQuery = repositoryService.createProcessDefinitionQuery()
                .latestVersion()
                .active()
```
I got nothing. The SQL printed is:
```sql
SELECT
	RES.* 
FROM
	ACT_RE_PROCDEF RES 
WHERE
	RES.VERSION_ = (
	SELECT
		max( VERSION_ ) 
	FROM
		ACT_RE_PROCDEF 
	WHERE
		KEY_ = RES.KEY_ 
		AND (
			( TENANT_ID_ IS NOT NULL AND TENANT_ID_ = RES.TENANT_ID_ ) 
			OR ( TENANT_ID_ IS NULL AND RES.TENANT_ID_ IS NULL ) 
		) 
	) 
	AND (
	RES.SUSPENSION_STATE_ = 1) 
```
I think maybe this:
```sql
SELECT
	RES.* 
FROM
	ACT_RE_PROCDEF RES 
WHERE
	RES.VERSION_ = (
	SELECT
		max( VERSION_ ) 
	FROM
		ACT_RE_PROCDEF 
	WHERE
		KEY_ = RES.KEY_ 
		AND (
			( TENANT_ID_ IS NOT NULL AND TENANT_ID_ = RES.TENANT_ID_ ) 
			OR ( TENANT_ID_ IS NULL AND RES.TENANT_ID_ IS NULL ) 
		) 
		AND (SUSPENSION_STATE_ = 1) 
	) 

```
![image](https://user-images.githubusercontent.com/23066241/102846909-3efe7980-444c-11eb-9746-6a9ea9e58426.png)

**Expected behavior**
Get v1 process deployment

**Additional context**
flowable: v6.6.0
database: mysql

**Comment by sscfaith** [comment] 2021-01-13 01:16
hello?

**Comment by tijsrademakers** [comment] 2021-11-02 15:39
Hi @sscfaith,  a unit test has been added to try and reproduce the issue. But we can't reproduce it. Therefore closing the issue, but please reopen when you can reproduce the issue in a unit test.

**Closed by tijsrademakers** 2021-11-02 15:39 UTC
