### ISSUE TITLE
All passwords should be encrypted

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#188] opened 2017-01-30 17:01 UTC
All passwords should be encrypted. API calls should expect only encrypted passwords. No clear text passwords should be read or accepted.

Thanks

**Comment by paulhh** [comment] 2017-01-31 09:17
Closing as not a bug and no discussion on the forums for the feature (see https://github.com/flowable/flowable-engine/wiki).

**Closed by paulhh** 2017-01-31 09:17 UTC
