### ISSUE TITLE
flowable docker localhost

### ISSUE THREAD

**Issue by wulinghui** [flowable/flowable-engine#1963] opened 2019-10-07 13:47 UTC
ip::8080/flowable-admin/   >>>  http://localhost:8080/flowable-idm/#/login?redirectOnAuthSuccess=true&redirectUrl=http://47.94.208.59:8080/flowable-modeler/

**Comment by tijsrademakers** [comment] 2020-01-18 21:41
Closing the issue because the description is lacking. Please reopen with a full description if the issue is still there.

**Closed by tijsrademakers** 2020-01-18 21:41 UTC
