### ISSUE TITLE
Add a documentation chapter on using EL in workflow definition

### ISSUE THREAD

**Issue by mgrouch** [flowable/flowable-engine#179] opened 2017-01-26 16:43 UTC
Add a documentation chapter on using EL in workflow definition.
It should cover most commonly used predefined spring beans their use,
and explain how EL can be written. How to concatenate strings EL, how to call functions, how to refer to constants. More examples please.

Thanks

**Comment by paulhh** [comment] 2017-01-31 09:20
Closing as not a bug and no discussion on the forums for the feature (see https://github.com/flowable/flowable-engine/wiki).

**Closed by paulhh** 2017-01-31 09:20 UTC
