### ISSUE TITLE
DbSqlSession may override existing key when insert entity

### ISSUE THREAD

**Issue by thkdog** [flowable/flowable-engine#3406] opened 2022-07-26 16:16 UTC
**Describe the bug**
`insertedObjects.get(clazz).put(entity.getId(), entity)` in `DbSqlSession` may override existing key silently, which is really hard to trace and debug the bug.

**Expected behavior**
Should avoid override or throw an Exception for what is happening, but not override the key silently.

**Additional context**
Flowable version: 6.5.0 to 6.7.2

The scene is somehow probabilistic the inserted values (etc. variables/candidate users or others) disappeared after start the process, and the possibility of occuarance can be about 10%.
I substitute the ID generator with the famous SnowFlake generator for distributed usage, but flowable is using cached bulk insert after ID generation, which makes it really fast and easy to trigger the issue.

**Comment by filiphr** [comment] 2022-07-27 05:55
@thkdog if the ID generator that you are using is generating duplicate IDs, then you have larger problems. It means that it can happen that you insert an entity with a duplicated ID.

>The scene is somehow probabilistic the inserted values (etc. variables/candidate users or others) disappeared after start the process, and the possibility of occuarance can be about 10%.

10% is a rather high chance of probability for generating duplicates. Can you please share the implementation of your `IdGenerator`? I think that your should look for a solution in that and not in the `DbSqlSession`. Can you also share this SnowFlake generator as well? We would like to have a look at it

**Comment by thkdog** [comment] 2022-07-27 07:07
> @thkdog if the ID generator that you are using is generating duplicate IDs, then you have larger problems. It means that it can happen that you insert an entity with a duplicated ID.
> 
> > The scene is somehow probabilistic the inserted values (etc. variables/candidate users or others) disappeared after start the process, and the possibility of occuarance can be about 10%.
> 
> 10% is a rather high chance of probability for generating duplicates. Can you please share the implementation of your `IdGenerator`? I think that your should look for a solution in that and not in the `DbSqlSession`. Can you also share this SnowFlake generator as well? We would like to have a look at it

Actually before using with Flowable, the ID generator has never produce the duplicated problem. The SnowFlake algorithm is initially raised by Twitter [https://blog.twitter.com/engineering/en_us/a/2010/announcing-snowflake](url).

We use use mybatis-plus [https://github.com/baomidou/mybatis-plus](url) as our orm layer, which is really popular in China and many other places, the generator algorithm it uses is based on SnowFlake [https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/incrementer/DefaultIdentifierGenerator.java](url) and the algorithm [https://github.com/baomidou/mybatis-plus/blob/1fb29af60ac52b8012385eb91085fcf1e0842a34/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/toolkit/Sequence.java#L34](url), and theoretically it produces 4095 unique id in 1ms.

I really don't understand how ID can be generated duplicated in Flowable cases, the problem arise like a flash. The surface of the problem shows like it lost some Candidates or Variables by chances like 10% (tested by script).
If I put even a conditional breakpoint around the `nextId()`, the problem just fly away permanently, but after run or deploy, it happens again. 

I think there must be something werid with the timing or maybe compiler and the way of inserting entities by flowable-engine(cached and batch-insert), the combitionation of these things trigger the problem, adding 1 more lines around the `nextId()` would fixed the problem.

Still, I think we should check the key existing, but not override silently, and I think the bug may just fly away after just checking existing key, it should give the generator a breath

**Comment by thkdog** [comment] 2022-07-27 07:11
Originally, the key existing checking should be handled by database, but the way flowable uses does silently override, which makes the problem covered deeply

**Comment by filiphr** [comment] 2022-07-27 07:21
Thanks for sharing the links. Flowable is using an implementation of our own [IdGenerator](https://github.com/flowable/flowable-engine/blob/main/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/cfg/IdGenerator.java). This means that this implementation is most likely incorrect. Can you share how that looks like?

**Comment by filiphr** [comment] 2022-07-27 07:27
In addition to sharing the implementation of the generator. Can you please provide a unit test which shows that this is failing?

**Comment by thkdog** [comment] 2022-07-27 07:40
> 

The generator used by us and mybatis-plus: [Generator](https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/incrementer/DefaultIdentifierGenerator.java)

**Comment by filiphr** [comment] 2022-07-27 07:57
@thkdog the generator you shared is not an implementation of the Flowable [`IdGenerator`](https://github.com/flowable/flowable-engine/blob/main/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/cfg/IdGenerator.java). Please share that implementation and a unit test showing the problem.

**Comment by thkdog** [comment] 2022-07-27 08:46
> @thkdog the generator you shared is not an implementation of the Flowable [`IdGenerator`](https://github.com/flowable/flowable-engine/blob/main/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/cfg/IdGenerator.java). Please share that implementation and a unit test showing the problem.

I rechecked the code, the Generator itself we used is good, the problem is caused how we call the `nextId()`, we initialize the generator instance every single call, which init the `sequence` inside the generator, this is the reason raise the issue.

Thanks for the discussion.

**Comment by filiphr** [comment] 2022-07-27 08:49
>I rechecked the code, the Generator itself we used is good, the problem is caused how we call the `nextId()`, we initialize the generator instance every single call, which init the `sequence` inside the generator, this is the reason raise the issue.

This means that your Flowable ID Generator implementation is not correct. If we look at the implementation in https://github.com/baomidou/mybatis-plus/blob/3.0/mybatis-plus-core/src/main/java/com/baomidou/mybatisplus/core/incrementer/DefaultIdentifierGenerator.java (the MyBatis plus code) you will see that the sequence is not instantiated on every single call.

Closing this issue, since the problem is not in Flowable, but in the implementation of the custom `IdGenerator`

**Closed by filiphr** 2022-07-27 08:49 UTC
