### ISSUE TITLE
Eclipse designer uses "activiti" namespace

### ISSUE THREAD

**Issue by boris-petrov** [flowable/flowable-engine#729] opened 2017-12-26 07:45 UTC
When saving a file with the Eclipse designer (plugin version 5.22.0) the file is full of "activiti:<something>" stuff while they should be "flowable:<something>". Am I missing something or is this a bug?

**Comment by sunilg27** [comment] 2018-01-05 10:07
As for as I understand, namespaces are used to differentiate the custom elements in the XML from usual types. I see that namespace is just a placeholder and it has very less significance in-terms of functionality. 

Any thoughts?

**Comment by boris-petrov** [comment] 2018-01-05 10:11
Well, I get runtime exceptions when trying to read the generated file with Flowable. If I change the "activiti:" things to "flowable:", then it works fine. So I guess it's not insignificant.

**Comment by tijsrademakers** [comment] 2018-01-05 10:12
Flowable supports both the activiti as well as the flowable namespace. But when using one of these namespace prefixes you have to make sure that there is a namespace declaration included in the BPMN XML as well.

**Comment by boris-petrov** [comment] 2018-01-08 10:30
I see. OK, I'll let you close the issue if you decide using "activiti" as namespace is fine. I would guess for consistency you could make the designer use "flowable". Thanks for the support!

**Comment by tijsrademakers** [comment] 2018-01-08 10:34
No, the issue is still valid, it should use the flowable namespace prefix. Thanks!

**Comment by moshahsa** [comment] 2018-04-18 08:57
Having same issue as well. Each time I make changes  with the Eclipse designer it changes the flowable namespace prefix to activiti. Would be nice if the designer uses flowable.

**Comment by tijsrademakers** [comment] 2020-01-18 21:57
Because of the focus on the engine development + the web modeler, closing this issue

**Closed by tijsrademakers** 2020-01-18 21:57 UTC
