### ISSUE TITLE
setVariable fails to take transient variable into account

### ISSUE THREAD

**Issue by franck102** [flowable/flowable-engine#2992] opened 2021-07-27 10:10 UTC
org.flowable.engine.impl.persistence.entity.ExecutionEntityImpl#setVariableLocal(java.lang.String, java.lang.Object, org.flowable.engine.impl.persistence.entity.ExecutionEntity, boolean)

should update the transient variable if one exists for the given name.
org.flowable.variable.service.impl.persistence.entity.VariableScopeImpl#hasVariableLocal does check & return true if a transient variable exists, so the implementation is inconsistent: the code today is saying "if there is a local 'foo' transient variable then let's create a 'foo' variable entity"

If the variable exists as a transient variable in the scope hasVariableLocal returns true:\
```
     if (transientVariables != null && transientVariables.containsKey(variableName)) {
            return true;
     }
```
However setVariableLocal proceeds with creating a new, non transient variable because it only checks for variable instances:

```
    if (variableInstance == null) {
                createVariableLocal(variableName, value, sourceExecution);
```

It leads to this behavior:

```
    execution.setTransientVariable("foo", "value1");
    execution.setVariable("foo", "value2");
    execution.getVariable("foo") -> returns value1
```

The implementation is also inconsistent with the documentation that states:

> A transient variable shadows a persistent variable with the same name.

**Comment by filiphr** [comment] 2021-08-09 11:50
I don't think that it is inconsistent with the documentation. From the documentation about [transient variables](https://flowable.com/open-source/docs/bpmn/ch04-API/#transient-variables) we can see the following:

>The following applies for transient variables:
>
> * There is no history stored at all for transient variables.
> * Like regular variables, transient variables are put on the highest parent when set. This means that when setting a variable on an execution, the transient variable is actually stored on the process instance execution. Like regular variables, a local variant of the method exists if the variable is set on the specific execution or task.
> * A transient variable can only be accessed before the next 'wait state' in the process definition. After that, they are gone. Here, the wait state means the point in the process instance where it is persisted to the data store. Note that an async activity is also a 'wait state' in this definition!
> * Transient variables can only be set by the setTransientVariable(name, value), but transient variables are also returned when calling getVariable(name) (a getTransientVariable(name) also exists, that only checks the transient variables). The reason for this is to make the writing of expressions easy and existing logic using variables works for both types.
> * A transient variable shadows a persistent variable with the same name. This means that when both a persistent and transient variable is set on a process instance and getVariable("someVariable") is called, the transient variable value will be returned.

It clearly says that a transient variable can only be set using the `setTransientVariable(name, value)` method, but they are also returned in the `getVariable(name)` call. 
The shadow part talks only about the `getVariable(name)` method, not about the `setVariable(name)` method.

In addition to that transient variables are only visible until the next wait state. Therefore, you need to explicitly set them, otherwise they would be persisted and visible to the next wait state. In your example after the transaction is completed and you do `execution.getVariable("foo")` you will get `value1` since this is what is persisted in the database.

If we do what you are saying there will no longer be a way for a user to persist a variable with a certain value for the next transaction is a transient variable exists.

Taking all of this into consideration, I am inclined to close this issue

**Comment by filiphr** [comment] 2021-08-17 07:08
Hey @franck102, we discussed this within the team and we believe that everything works as designed. We have no intention in changing the functionality of `setVariable` currently. Therefore, I am closing this issue.

**Closed by filiphr** 2021-08-17 07:08 UTC

**Comment by franck102** [comment] 2021-08-19 16:33
Fair enough, you are making valid points.
