### ISSUE TITLE
Error terminating when publishing to k8s

### ISSUE THREAD

**Issue by leobling** [flowable/flowable-engine#3501] opened 2022-10-21 09:02 UTC
After the jar package of the UI is integrated through spring boot, when it is published to the K8S, the running is terminated with an error

The local localhost environment can run normally

![image](https://user-images.githubusercontent.com/116346305/197157361-51d8c36e-d831-4919-b453-861daef35e5d.png)

![image](https://user-images.githubusercontent.com/116346305/197157492-de83f3a5-21e3-475d-b33a-6653d28f4614.png)

**Comment by yvoswillens** [comment] 2022-10-21 10:49
Hi.

Why do you think this is Flowable related?
The application seems to boot up fine.
Although I'm not able to determine this for sure (based on the info you provide) this looks like a pod that is being terminated because it does not become 'healthy' in the set time.

This can be caused by many different Kubernetes related configurations.
Are you using the Flowable Helm charts? Or do you do something custom?

Regards,

Yvo

**Comment by yvoswillens** [comment] 2022-10-24 06:31
I'm closing this for now.
Please use the forum for additional help.
Or reopen this issue if you have clear pointers that this is Flowable related.

**Closed by yvoswillens** 2022-10-24 06:31 UTC
